### ISSUE TITLE
Account for metatag prefixes when searching/linking

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4965] opened 2022-01-18 16:32 UTC
Example:
* A link to [[char:character_name]] should lead to [[character_name]], not to the literal char:character_name. It should also be colored accordingly. The link should still be displayed as "char:character_name" for clarity, especially for BURs
* Searching for char:character_name in posts and wikis should search for character_name, not the literal version

Related: issue #4919

**Comment by BrokenEagle** [comment] 2022-01-19 00:15
Is this something that needs to be fixed in the DText ragel parser, or done afterwards in the postprocess function of the `dtext.rb` module? Either way could work, although I think doing it with Danbooru would be easier, plus the ragel parser could be used by others, and they may not necessarily have the same tag category metatags.

**Comment by evazion** [comment] 2022-01-20 07:04
Using `char:character_name` in alias requests is not intended behavior and that it works at all is pure accident. The only place it's intended to work is when tagging posts. I'd rather forbid it everywhere else.

Allowing it in DText permits weird things, like writing `[[artist:touhou]]` and having it link to the Touhou wiki, even though it's not an artist tag.

**Closed** 2022-09-10 09:50 UTC
Labels: Alteration
