### ISSUE TITLE
Uploading from DeviantArt doesn't work

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4431] opened 2020-04-29 22:01 UTC
When fetching the link this error shows:
```
bad argument (expected URI object or URI string)
```

The artist, as well as the DA tags are fetched correctly.
Upon uploading a new message shows up:
```
Upload #2914215
Date: 2020-04-29 17:57:25 -0400
An error occurred: error: NoMethodError - undefined method `hostname' for nil:NilClass

    app/logical/downloads/file.rb:97:in `is_cloudflare?'
    app/logical/downloads/file.rb:66:in `uncached_url'
    app/logical/downloads/file.rb:31:in `download!'
    app/logical/upload_service/utils.rb:190:in `get_file_for_upload'
    app/logical/upload_service.rb:51:in `start!'
    app/controllers/uploads_controller.rb:55:in `create'
```

**Comment by lllusion3469** [comment] 2020-04-29 23:16
This is more or less a duplicate of #4219 but that one is still closed so...

Some time ago DA thought they had to redesign their site for some reason and removed the `<meta property="da:appurl" content="DeviantArt://deviation/$UUID"/>` tag in the process which the old strategy needed to use the API (which they broke later too, but it's fixed now, I think).

This was fixed by using the JS backend to fetch the metadata (#4144) which worked for a while until they started requiring the user to login to download images (which is what #4219 is about).

A workaround was login manually in a browser, export the cookies, and use those in the strategy. You would need update those when the server sent you new ones and invalidated the old ones which happened regularly.

I implemented (and posted) a ugly workaround using a `cookies.txt` file on the file system and @evazion adapted it to use redis instead which never quite worked for a few reasons I noted in #4219 and ea718122daeaedb949649808f4bcf0f5d020a462. I'm guessing he gave up on it (or it wasn't important enough) since he never answered.

[Some weeks ago](https://github.com/danbooru/danbooru/issues/4219#issuecomment-598962708) I noticed that DA added back the `<meta property="da:appurl" content="DeviantArt://deviation/$UUID"/>` tag ([with some limitations](https://github.com/mikf/gallery-dl/commit/c874684f0573ce994c0be911984ff001fc953653#diff-a40d97fd5b1906e91454c7a6d31a579a)) which should enable us to go back to the actual API.

I thought about implementing this myself but I haven't yet (obviously) for several reasons:
* my workaround still works fine for me on my instance (not a blocker for me)
* hardly anyone seems to care
* some design decisions
  * scrape HTML to get the uuid and use the API for metadata + download (works for sta.sh as well)
  * use JS backend for metadata + uuid and API for downloading (most certainly won't work with sta.sh unless I missed something)
  * use JS backend for uuid and API for metadata + download (would mostly work with sta.sh)

There are some minor problems with using the JS backend for metadata:
* it could change at any moment
* some non-downloadable image urls are more complicated to get e.g. flash: compare for [this post](https://www.deviantart.com/heartgear/art/SL-40v3-522007633)
  * API: `https://api-da.wixmp.com/_api/download/file?downloadToken=$SOMECENSOREDTOKEN`
  * JS: `https://sandbox.deviantart.com?fileheight=1126&filewidth=750&filename=wixmp%3Af%2Fea95be00-c5aa-4063-bd55-f5a9183912f7%2Fd8msfo1-09d19d8d-86bf-42a2-a1cc-650a959aaeeb.swf`
* doesn't work with sta.sh, which at least I do care about
  * you can't reconstruct the sta.sh url from the image url - you can't even tell it was from sta.sh in the first place and not from DA
  * it's way more convenient to use the bookmarklet

**Closed** 2020-05-11 21:22 UTC
Labels: Bug
