### ISSUE TITLE
Occassionally fetching Tumblr samples

### ISSUE THREAD

**Issue by kagayakushininggate** [danbooru/danbooru#5630] opened 2024-01-22 11:56 UTC
Uploaded https://danbooru.donmai.us/media_assets/18506270 from 
https://64.media.tumblr.com/02cf936dcb80b8f2a2c0f264b7470e6b/2d5da44ca2475c90-01/s400x600/3bb75f736f02fbc53a804f6ff76a9c8de27a450c.pnj ; got a 79.4 KB .jpg, 695x443.

Uploaded https://danbooru.donmai.us/media_assets/18506279 from https://goomyloid.tumblr.com/post/716716986355384320 ; got a 229 KB .png, 695x443.
Both are from the same Tumblr post.

**Comment by evazion** [comment] 2024-04-14 17:19
Duplicate of #5503.

**Closed by evazion** 2024-04-14 17:19 UTC
Labels: Source Support
