### ISSUE TITLE
wildcard searches yield wrong results when no matches

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4778] opened 2021-03-27 18:40 UTC
example:
[/counts/posts?tags=nosuchtag*](https://danbooru.donmai.us/counts/posts?tags=nosuchtag*)
```
Post count for nosuchtag*: 4403927
```

when there *are* matches, it works fine:
[/counts/posts?tags=mtd_*](https://danbooru.donmai.us/counts/posts?tags=mtd_*)
```
Post count for mtd_*: 6 
```

**Comment by Thayol** [comment] 2021-06-16 21:03
Dupe of issue #4435

**Closed** 2021-06-16 21:04 UTC
Labels: Bug
