### ISSUE TITLE
Tags with empty/deleted wikis can be deprecated

### ISSUE THREAD

**Issue by NamelessContributor** [danbooru/danbooru#5616] opened 2024-01-08 12:59 UTC
Steps to reproduce:
- Create a tag
- Create a wiki
- Empty the wiki and delete it
- Empty the tag
- The tag can now be deprecated effectively without requiring a wiki

**Comment by nottalulah** [comment] 2024-01-08 15:40
Dupe of #5183

**Closed** 2024-01-08 15:41 UTC
