### ISSUE TITLE
KeyError when trying to view tag history

### ISSUE THREAD

**Issue by kittey** [danbooru/danbooru#5190] opened 2022-05-27 15:32 UTC
Attempting to view the tag history of [post #10595](https://danbooru.donmai.us/posts/10595) results in the following exception:

```
    KeyError exception raised
    app/models/post_version.rb:154:in `pretty_rating'
    app/helpers/post_versions_helper.rb:46:in `post_version_field'
    app/views/post_versions/_listing.html.erb:22
    app/logical/table_builder.rb:66:in `value'
    app/views/table_builder/_table.html.erb:17
    app/views/table_builder/_table.html.erb:16
    app/views/table_builder/_table.html.erb:15:in `each'
    app/views/table_builder/_table.html.erb:15:in `each_with_index'
    app/views/table_builder/_table.html.erb:15
    app/views/table_builder/_table.html.erb:14
    app/views/table_builder/_table.html.erb:13:in `each_with_index'
    app/views/table_builder/_table.html.erb:13
    app/views/table_builder/_table.html.erb:1
    app/helpers/application_helper.rb:278:in `table_for'
    app/views/post_versions/_listing.html.erb:6
    app/views/post_versions/index.html.erb:33
    app/controllers/application_controller.rb:64:in `respond_with'
    app/controllers/post_versions_controller.rb:19:in `index'
    app/controllers/post_versions_controller.rb:36:in `set_timeout'
```

Tried a few other posts’ tag histories as well: some are fine (10594), some are broken (10596).

**Comment by nottalulah** [comment] 2022-05-27 15:33
dupe of #5181. already fixed in betabooru

**Comment by nonamethanks** [comment] 2022-05-27 15:33
See https://betabooru.donmai.us/post_versions?search%5Bpost_id%5D=10595

**Closed by nonamethanks** 2022-05-27 15:33 UTC
