### ISSUE TITLE
Canonical example image(s) for tag wikis

### ISSUE THREAD

**Issue by pokeball99** [danbooru/danbooru#5581] opened 2023-09-21 02:45 UTC
Like #4828 and #4934, this is another attempt to improve understanding of what the community thinks of a particular tagged concept. Currently the most recent 5 posts tagged are displayed as previews for a given tag, but this this not a flawless system as it has been noted many times of glaring mistags being showed, which is not great for people who are potentially looking at this tag for the first time.
It has been proposed in the discord in the past to set particular posts as "canonical" examples of a given tag. i would also suggest perhaps during the implementation of this to also be able to put "counter examples" of posts that some might tag as a particular tag, but are not actually valid, and potentially better off with another tag.

An absolute max limit of canonical posts i would suggest either to be either 10, 20 or 50, as to prevent people from abusing it or causing needless bloat. I would also suspect it would be vital to be able to allow the locking down of these examples by mods in case of users managing to abuse it anyways.

**Comment by evazion** [comment] 2024-03-28 18:42
This is essentially a duplicate of #4828, which has been implemented.

**Closed by evazion** 2024-03-28 18:42 UTC
Labels: Feature
