### ISSUE TITLE
Autocomplete Broken For Tag Category Metatags

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4919] opened 2021-11-11 15:40 UTC
First mentioned on [forum #198281](https://danbooru.donmai.us/forum_posts/198281). Trying to do autocomplete with any of the tag category prefixes no longer works. This is with all userscripts disabled, on both Chrome and Firefox.

**Example:** `copyright:fate_(series)`

Of note, this should only be fixed for tag edit inputs, since tag query inputs do not support the tag category metatags at this time. For example, searching `copy:girls_und_panzer` will bring up no results. This should probably not be changed, since the tag category metatags hold no meaning when used as part of a query.

**Comment by evazion** [comment] 2022-08-30 02:02
Duplicate of #4752. This was fixed in 031ab1e833.

**Closed by evazion** 2022-08-30 02:02 UTC
Labels: Bug
