### ISSUE TITLE
Verifying account does not remove restricted status

### ISSUE THREAD

**Issue by AlexCSDev** [danbooru/danbooru#4739] opened 2021-02-27 15:42 UTC
When I registered I somehow triggered "You must verify your account because you signed up from a proxy or a VPN." message. Even after verification my account status is still "restricted" despite having a green checkmark near my email address.

**Comment by nonamethanks** [comment] 2021-02-28 01:22
@AlexCSDev could you post your account name, or send it via DM to me or evazion on the [Danbooru Discord](https://discord.com/invite/danbooru) or via Danbooru DMail if you don't want to post it publicly?

**Comment by AlexCSDev** [comment] 2021-02-28 13:48
@nonamethanks I've sent a message to evazion via discord. It appears that DMail is not available for restricted accounts.

**Comment by nonamethanks** [comment] 2021-08-07 12:28
Closing this. It appears the issue is with non-trusted domains, so not really an issue.

**Closed by nonamethanks** 2021-08-07 12:28 UTC
Labels: Bug
