### ISSUE TITLE
Mass-update/Alias *_(cosplay) of character tags on alias creation

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3409] opened 2017-11-29 17:49 UTC
First made a note of this issue [on Danbooru](http://danbooru.donmai.us/forum_posts/126933) several months ago.

> BrokenEagle98 said:
>
> Not exactly a bug, but I have encountered an unthought of situation in regards to the *_(cosplay) tag. Whenever a character tag gets renamed, either manually or through an alias, it does not rename the corresponding *_(cosplay) tag.
> 
> In either case, it adds a tag that should not be added whenever the post gets updated. In the latter case, it adds the consequent to an alias, a tag that can not otherwise normally be added, and that can only be searched with with the raw addon.

This [issue came up again](http://danbooru.donmai.us/forum_posts/139941) because of a recent alias request.

> ghostrigger said:
>
> regarding the recent topic #14734 , noticed that there were some leftover posts (about 20+) that the batch process failed to execute particularly on sakura_saber_(cosplay) and assassin_of_black_(cosplay).
> 
> the result is, despite the move to new tags, old char_(cosplay) tags remained together with the old char tags.
> 
> the old tags register an already post count of zero but this is not true. when we append "&raw=true" to the url and check the tag correction on the "fix" link the true count shows.
> 
> would suspect that's why the batch process proceeded on here but not here . i assume that on the latter was not a simple delayed job, done manually and outside intervention since the time difference of two day after the batch was initially ran.
> 
> would recommend that exact count checking be done automatically before batch processes are run.
> 
> did not check other mass updates.

So either run a mass update moving the old cosplay tag to the new one, or create an alias doing the same.  I'm not sure how the timing will work on this one though, i.e. will different results be achieved if the *_(cosplay) fix is run before the character fix, or vice versa.  It would probably need to be tested.

**Comment by evazion** [comment] 2017-12-01 17:56
Part of the problem is that `<character>_(cosplay)` tags don't apply aliases to the character tag. I guess we need to apply aliases twice, first to the `<character>_(cosplay)` tag and then to `<character>` tag itself.

**Comment by evazion** [comment] 2017-12-06 18:56
> Part of the problem is that <character>_(cosplay) tags don't apply aliases to the character tag.

d6d7340 fixes this. Makes it so that adding e.g. `sakura_saber_(cosplay)` adds `okita_souji_(fate)`, not `sakura_saber`.

It might be better to make it so that `TagAlias.to_aliased` automagically aliases `<character>_(cosplay)` tags. That is, `TagAlias.to_aliased("sakura_saber_(cosplay)")` would return `okita_souji_(fate)_(cosplay)`, even when `sakura_saber_(cosplay) -> okita_souji_(fate)_(cosplay)` doesn't exist.

**Comment by evazion** [comment] 2019-08-15 22:32
Remaining issue: mass updates and aliases of character tags should move _(cosplay) tags.

**Comment by nonamethanks** [comment] 2020-12-04 09:54
> Remaining issue: mass updates and aliases of character tags should move _(cosplay) tags.

This is fixed now so unless I'm mistaken it can be closed.

**Closed by nonamethanks** 2020-12-04 09:54 UTC
Labels: Feature, Low Priority
