### ISSUE TITLE
Aliasing two tags with the same implication to the same tag blocks the second alias

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4871] opened 2021-09-01 13:53 UTC
See https://danbooru.donmai.us/forum_topics/19350

Both tags had the "gigantamax" implication, so when it tried to alias the second one it failed because it already existed in the consequent tag due to the first move, and thus made the whole BUR fail.

If an implication already exists we should just silently ignore it in this case.

**Comment by evazion** [comment] 2022-01-11 22:40
https://testbooru.donmai.us/forum_topics/3

I can't reproduce, it seems to be working now. It might have been fixed in 9ba84efc? That's the only major recent change to BURs.

**Closed by evazion** 2022-01-11 22:40 UTC
Labels: Bug
