### ISSUE TITLE
Errors showing up when upvoting or downvoting on comments with embedded images

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5684] opened 2024-04-24 00:11 UTC
The issue is as follows:

1. Upvote or downvote on any comment with an embedded image
2. the following error shows up: `Unexpected error: NoMethodError` - the score will not show as having changed until you refresh the page or leave the page and come back
3. If you click on the same upvote/downvote button again while the NoMethodError is on the page, an `Access Denied` error will pop up

**Comment by evazion** [comment] 2024-04-25 05:10
Duplicate of #5669.

**Closed by evazion** 2024-04-25 05:10 UTC
