### ISSUE TITLE
Submitting an artist update creates a new version even if no changes have been made

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4809] opened 2021-06-01 02:46 UTC
The following is not the only time, but the most recent occurrence.

**Example:** https://danbooru.donmai.us/artist_versions?search[id]=922287

**Comment by nonamethanks** [comment] 2021-06-21 12:59
That happens with every version, including post edits. issue #4354

**Comment by luni3359** [comment] 2021-06-25 02:37
If the underlying problem is the same, this issue should be closed in preference of the earlier one.

**Comment by evazion** [comment] 2022-01-20 06:24
I can't reproduce this. I assume these were caused by version merging, as per #4354.

**Closed by evazion** 2022-01-20 06:24 UTC
Labels: Bug
